#!/usr/bin/env python3
"""Regenerate src/lib/portrait-images.ts.

Scans public/images for portrait-orientation raster images (taller than wide)
and emits the PORTRAIT_IMAGE_DIMS module that ArticlePageClient uses to render
those images at natural aspect ratio instead of cropping them into the
landscape object-cover bands. Deterministic: sorted by path.
"""
import os
import sys

from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG_DIR = os.path.join(REPO, "public", "images")
OUT = os.path.join(REPO, "src", "lib", "portrait-images.ts")

EXTS = (".webp", ".jpg", ".jpeg", ".png")

HEADER = """/**
 * Generated by scripts/generate_portrait_module.py - do not edit by hand.
 * Dimensions of every portrait (taller than wide) image in public/images.
 * ArticlePageClient renders these at natural aspect ratio, centred, so
 * full-length people photos are never decapitated by the landscape
 * object-cover bands. Re-run the generator after adding portrait images.
 */
export const PORTRAIT_IMAGE_DIMS: Record<string, { width: number; height: number }> = {
"""


def main() -> int:
    entries = []
    for name in sorted(os.listdir(IMG_DIR)):
        if not name.lower().endswith(EXTS):
            continue
        path = os.path.join(IMG_DIR, name)
        try:
            with Image.open(path) as im:
                w, h = im.size
        except Exception as e:  # noqa: BLE001
            print(f"skip {name}: {e}", file=sys.stderr)
            continue
        if h > w:  # portrait only
            entries.append((f"/images/{name}", w, h))
    lines = [f'  "{p}": {{ width: {w}, height: {h} }},' for p, w, h in entries]
    body = HEADER + "\n".join(lines) + "\n};\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"wrote {OUT}: {len(entries)} portrait images")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
