"""Evidence Engine v0.1 facility-level bands (from evidence-engine-v01-report.json,
run 2026-09-21, rebanded 0.55/0.20 thresholds). Baseline for ledger entries."""

V01_BAND = {
    "ixafrica-nbox1": "unsupported",
    "ixafrica-nbox1-2": "unsupported",
    "ixafrica-tilisi": "unsupported",
    "africa-dc-nairobi-1": "review",
    "africa-dc-nairobi-2": "unsupported",
    "safaricom-dc-waiyaki": "unsupported",
    "safaricom-thika": "unsupported",
    "safaricom-red-hill": "unsupported",
    "microsoft-g42-ai-dc": "unsupported",
    "telkom-milimani-nairobi": "unsupported",
    "telkom-telephone-house-nairobi": "unsupported",
    "liquid-nairobi": "unsupported",
    "icolo-nbo1": "unsupported",
    "icolo-nbo2": "review",
    "icolo-mba1": "review",
    "icolo-mba2": "unsupported",
    "paix-nairobi": "review",
    "konza-national-dc": "unsupported",
    "telkom-telephone-house-mombasa": "unsupported",
    "seacom-mombasa-cls": "unsupported",
    "simbanet-nairobi": "unsupported",
    "raxio-nairobi": "unsupported",
    "septris-nairobi": "unsupported",
    "global-ts-nairobi": "unsupported",
    "wananchi-nairobi": "unsupported",
    "kenya-data-centres-sme": "unsupported",
    "nxtra-tatu-city": "review",
    "raxio-kampala-ug1": "unsupported",
    "uganda-national-data-centre": "unsupported",
    "raxio-dar-es-salaam-tz1": "unsupported",
    "africa-data-centres-kigali-kgl1": "review",
}
